
###login admina
POST http://localhost:8085/api/login
Content-Type: application/json

{
    "email":"admin@admin.sk",
    "password":"admin123"
}
### get all users (only admin)
GET  http://localhost:8085/api/users
Content-Type: application/json

{
}
### get one user with id (only admin)
GET  http://localhost:8085/api/users/1
Content-Type: application/json

{
}
### create user (only admin)
POST http://localhost:8085/api/users
Content-Type: application/json

{
    "email":"testUser1234@testUser.sk",
    "password":"User1234",
    "idGefco": "048751481.649",
    "admin": false,
    "name": "USERKO"
}
### update user (only admin)
POST http://localhost:8085/api/users/2
Content-Type: application/json

{
    "email":"testUser1234@testUser.sk",
    "password":"User1234",
    "idGefco": "048751481.649",
    "admin": false,
    "name": "USERdKOK"
}
### login not admin
POST http://localhost:8085/api/login
Content-Type: application/json

{
    "email":"testUser1234@testUser.sk",
    "password":"User1234"
}
### change passwort for not admin
POST http://localhost:8085/api/users/change-password
Content-Type: application/json

{
    "oldPassword":"User1234",
    "newPassword":"User1234"
}
### get order with id 
GET  http://localhost:8085/api/order/1
Content-Type: application/json

{
}
### get all orders of logged user / all orders in system for admin
GET  http://localhost:8085/api/order
Content-Type: application/json

{
}

