
###login admina
POST http://localhost:8085/api/login
Content-Type: application/json

{
    "email":"Admin@admin.sk",
    "password":"admin123"
}
### get all users (only admin)
GET  http://localhost:8085/api/users
Content-Type: application/json

{
}
### get one user with id (only admin)
GET  http://localhost:8085/api/users/2
Content-Type: application/json

{
}
### create user (only admin)
POST http://localhost:8085/api/users
Content-Type: application/json

{
    "email":"adagon001@gmail.com",
    "password":"User1234",
    "idGefco": "048751481.649",
    "admin": false,
    "name": "USERKO"
}
### update user (only admin)
POST http://localhost:8085/api/users/1
Content-Type: application/json

{
    "email":"testUser1234@testUser.sk",
    "password":"User1234",
    "idGefco": "048751481.649",
    "admin": false,
    "name": "USERdKOK"
}
### delete user (only admin)
DELETE  http://localhost:8085/api/users/1
Content-Type: application/json

{
}
### login not admin
POST http://localhost:8085/api/login
Content-Type: application/json

{
    "email":"adagon001@gmail.com",

    "password":"Adamko"
}
### get logged user not admin
GET http://localhost:8085/api/userss/logged-user
Content-Type: application/json

{
}
### change passwort for not admin
POST http://localhost:8085/api/users/change-password
Content-Type: application/json

{
    "oldPassword":"admin123",
    "newPassword":"admin123"
}
### get order with id 
GET    http://localhost:8085/api/order/1
Content-Type: application/json

{
}
### export selected
POST http://localhost:8085/api/order/export
Content-Type: application/json

{
    "idArray":[1,2]
}
### export all user`s orders
GET  http://localhost:8085/api/order/export
Content-Type: application/json

{
}
### get all orders of logged user / all orders in system for admin
GET  http://localhost:8085/api/order
Content-Type: application/json

{
}
### reset forgotten password 
POST  http://localhost:8085/api/password-reset
Content-Type: application/json

{
    "email":"adagon001@gmail.com"
}
### reset forgotten password 
POST  http://localhost:8085/api/password-reset/22/ad505cd0827031de8023f7d9fe9c9ad9f50785ed1cc742c0698a466b08738015
Content-Type: application/json

{
    "password":"Adamko"
}