

POST http://localhost:8085/api/login
Content-Type: application/json

{
    "email":"admin@admin.sk",
    "password":"admin123"
}
###
POST http://localhost:8085/api/users
Content-Type: application/json
Cookie: SESSIONID=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkVXNlcnMiOiIxIiwiaWRHZWZjbyI6IjAiLCJlbWFpbCI6ImFkbWluQGFkbWluLnNrIiwibmFtZSI6IkFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTAkdnpTdWVFRnZycXpkMUdBbDd4eXBNT3g3YTgwWHcwVmxzbGk2WHEuN0kvNDhvYzR5MzFXSy4iLCJhZG1pbiI6dHJ1ZSwicmVzZXRUb2tlbiI6bnVsbH0sImlhdCI6MTYzNzI0NjU5OH0.l5FiTQsIz8pssL4GYpZi9kU86sOPMWAt9YqCyEYQmg8; Path=/; HttpOnly;

{
    "email":"testUser1@testUser.sk",
    "password":"User123",
    "idGefco": 25,
    "admin": false,
    "name": "Jozo"
}
###
GET  http://localhost:8085/api/users
Content-Type: application/json
Cookie: SESSIONID=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyIjp7ImlkVXNlcnMiOiIxIiwiaWRHZWZjbyI6IjAiLCJlbWFpbCI6ImFkbWluQGFkbWluLnNrIiwibmFtZSI6IkFkbWluIiwicGFzc3dvcmQiOiIkMmIkMTAkdnpTdWVFRnZycXpkMUdBbDd4eXBNT3g3YTgwWHcwVmxzbGk2WHEuN0kvNDhvYzR5MzFXSy4iLCJhZG1pbiI6dHJ1ZSwicmVzZXRUb2tlbiI6bnVsbH0sImlhdCI6MTYzNzI0NjU5OH0.l5FiTQsIz8pssL4GYpZi9kU86sOPMWAt9YqCyEYQmg8; Path=/; HttpOnly;

{
}

